imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

easy_admin:
    entities:
        User:
            class: AppBundle\Entity\User
            list:
              fields: ['id', 'name', 'phone', {property:'email',label:'Email'},{property:'city',label:'City'},{property:'street',label:'Street'},{property:'dom',label:'dom'}]
              title: 'User details'
              actions: ['-new',{ name: 'show', label: 'Show' },'-edit',{ name: 'search', label: 'Search' }]
            show:
                title: 'User details'
                fields: ['id', 'name', 'phone', {property:'email',label:'Email'},{property:'city',label:'City'},{property:'street',label:'Street'},{property:'dom',label:'dom'}]
                actions: ['-edit',{ name: 'delete', label: 'Delete' },{ name: 'list', label: 'BACK TO LIST' }]
            new:
              fields: ['name', 'phone', 'email']
        Order:
            class: AppBundle\Entity\Order
            list:
                title: 'Order details'
                fields: ['id',  {property:'user.name',label:'Name'}, {property:'user.phone',label:'Phone'},{property:'product.test',label:'Product Name'}, {property:'count',label:'Count'}, {property:'date',label:'Date'}]
                actions: [{name: 'show', label: 'Show' },'-edit','-new',{ name: 'search', label: 'Search' }]
            show:
                title: 'Order'
                fields: ['id',  {property:'user.name',label:'Name'}, {property:'user.phone',label:'Phone'},{property:'product.test',label:'Product'}, {property:'count',label:'Count'}, {property:'date',label:'Date'}]
                actions: ['-edit',{ name: 'delete', label: 'Delete' },{ name: 'list', label: 'BACK TO LIST' }]
        Catagory:
            class: AppBundle\Entity\Category
            list:
                fields: [ id,name,{property:'pic',label:'Picture',type:'image'}]
                title: 'Category details'
                actions: [{name: 'show', label: 'Show' },{ name: 'edit', label: 'Edit' },{ name: 'search', label: 'Search' },{ name: 'new', label: 'add Catagory' }]
            show:
                title: 'Catagory'
                fields: [ id,name,{property:'pic',label:'Picture',type:'image'}]
                actions: [{ name: 'delete', label: 'Delete' },{ name: 'edit', label: 'Edit' },{ name: 'list', label: 'BACK TO LIST' }]
            edit:
                title: 'Catagory Edit'
                fields: [name,pic]
                actions: [{ name: 'delete', label: 'Delete' },{ name: 'list', label: 'BACK TO LIST' }]
        SubCatagory:
            class: AppBundle\Entity\SubCat
            list:
                fields: [ id ,name,atribute,{property:'picture',label:'Picture',type:'image'},{property:'catId',label:'Category'}]
                title: 'SubCatagory details'
                actions: [{name: 'show', label: 'Show' },{ name: 'edit', label: 'Edit' },{ name: 'new', label: 'Add Sub' },{ name: 'search', label: 'Search' }]
            show:
                title: 'SubCatagory'
                fields: [ id ,name,atribute,{property:'picture',label:'Picture',type:'image'},{property:'catId',label:'Category'}]
                actions: ['-show',{ name: 'delete', label: 'Delete' },{ name: 'edit', label: 'Edit' },{ name: 'list', label: 'BACK TO LIST' }]
            edit:
                actions: [{ name: 'delete', label: 'Delete' },{ name: 'list', label: 'BACK TO LIST' }]
                fields: [name,atribute,'picture',{property:'catId',label:'Category'}]

        Products:
            class: AppBundle\Entity\Product
            list:
                title: 'Products details'
                fields: [ id ,{property:'test',label:'Name'},subId,info,price,{property:'picture',label:'Picture',type:'image'}]
                actions: ['-show',{ name: 'edit', label: 'Edit' },{ name: 'new', label: 'Add Product' },{ name: 'search', label: 'Search' }]
            edit:
                title: 'Product Edit'
                actions: ['-show',{ name: 'edit', label: 'Edit' },{ name: 'delete', label: 'Delete' },{ name: 'list', label: 'BACK TO LIST' }]
                fields: [{property:'test',label:'Name'},subId,info,price,'picture']

